### ISSUE TITLE
GitHowTo

### ISSUE THREAD

**Issue by StarterEventPlatform** [StarterEventPlatform/glduTest#1]
Пройти курс: https://githowto.com/ru

**Comment by GlebDurygin** [comment]
•	git add – indexation of changes
•	git status – check condition
•	git commit –m “Commit”
•	git log – show log
•	git log –pretty=oneline – show only names of commits
•	git checkout – cross on branches
•	git tag – set tag name
•	git checkout hello.html – cancel changes in files before indexation
•	git reset HEAD hello.html – cancel changes in files after indexation
•	git revert – cancel commit
•	git reset --hard v1 – remove all new commits to v1
•	git tag –d v1 – remove tag v1
•	git commit –amend –m “Change previous commit” – change previous commit
•	git checkout –b style – create branch style
•	git merge master – merge branches style and master
•	git pull – git fetch, git merge
•	git push
