### ISSUE TITLE
Изучить модель

### ISSUE THREAD

**Issue by StarterEventPlatform** [StarterEventPlatform/glduTest#2]
Изучить статью: https://habr.com/post/106912/

**Comment by GlebDurygin** [comment]
git pull – pick up changes from origin branch
git push – upload your changes to origin branch
Central repository consists of two main branches: master and develop. The main branch is origin/master. 
Changes in origin/master branch = new release. 
Support branches: Feature, Release, Hotfix
•	Feature branches: May originate from: develop; Should be poured into: develop
For developing new functions
Create a new feature branch: $ git checkout –b myfeature develop
Add completed feature branch to develop: $ git checkout develop ; $ git merge –no-ff myfeature; git branch –d myfeature; git push origin develop
•	Release branches: May originate from: develop; Should be poured into: develop and master
Used to prepare for the release of new versions.
New release branch: $ git checkout –b release-1.2 develop; $ ./bump-version.sh 1.2; $ git commit -a -m "Bumped version number to 1.2"
•	Hotfix branches: May originate from: master; Should be poured into: develop and master
immediate fix bugs
New hotfix branch: $ git checkout -b hotfix-1.2.1 master; $ ./bump-version.sh 1.2.1; $ git commit -a -m "Bumped version number to 1.2.1"
Fix bug: $ git commit -m "Fixed severe production problem"
Move changes to master and develop
Delete hotfix brunch: $ git branch -d hotfix-1.2.1
