### ISSUE TITLE
Учимся склеивать коммиты

### ISSUE THREAD

**Issue by StarterEventPlatform** [StarterEventPlatform/glduTest#3]
Для того, чтобы удобно следить за изменениями в проекте - необходимо, чтобы коммиты были в приличном состоянии.

Для этого:

1. Понять смысл 1 коммит - 1 изменение
2. Научиться склеивать коммиты
3. Откатывание коммита
4. Научиться справляться с конфликтами при мерже веток вручную

**Comment by GlebDurygin** [comment]
1) https://habr.com/post/183646/
feature - used when adding new application level functionality
fix - fix some serious bug
docs - everything related to documentation
style - fix typos, fix formatting
refactor - refactoring application code
test - everything related to testing
chore - usual maintenance code
2) git rebase
3) git reset --hard v1 – remove all new commits to v1
git revert – cancel commit
